from typing import List
import random
import re

def extract_answered_choice(model_response: str) -> int:
    '''Extracts the answered choice from the model response.

    Args:
        model_response (str): The response from the model.

    Returns:
        int: The answered choice. 0:A, 1:B, 2:C, 3:D, 4:E
    
    Raises:
        ValueError: If the model response does not start with 'Answer:' or if the model response does not include A, B, C, D, or E at the end.
    '''

    # strip the response
    model_response = model_response.strip()
    model_response = model_response.replace('*', '') # bold and italics

    # take the last character
    last_char = model_response[-1]
    last_char.upper()
    if last_char == 'A':
        return 'A'
    elif last_char == 'B':
        return 'B'
    elif last_char == 'C':
        return 'C'
    elif last_char == 'D':
        return 'D'
    elif last_char == 'E':
        return 'E'
    else:
        print("bad response!", last_char)
        # answer randomly
        return random.choice(['A', 'B', 'C', 'D', 'E'])
        # raise ValueError("Model response does not include A, B, C, D, or E at the end.")

# TODO: rename to extract_choice_from_answer()
def extract_answered_choice_old(model_response: str) -> int:
    '''Extracts the answered choice from the model response.

    Args:
        model_response (str): The response from the model.

    Returns:
        int: The answered choice. 0:A, 1:B, 2:C, 3:D, 4:E
    
    Raises:
        ValueError: If the model response does not start with 'Answer:' or if the model response does not include A, B, C, D, or E at the end.
    '''

    last_line = model_response.split('\n')[-1]

    if last_line.startswith('Answer:'):
        last_line = last_line[len('Answer:'):].strip()
    else:
        print("bad response!")
        return 'A'
        # raise ValueError("Model response does not start with 'Answer:'")

    if last_line.startswith('A'):
        return 'A'
    elif last_line.startswith('B'):
        return 'B'
    elif last_line.startswith('C'):
        return 'C'
    elif last_line.startswith('D'):
        return 'D'
    elif last_line.startswith('E'):
        return 'E' 
    else:
        print("bad response!")
        return 'A'
        # raise ValueError("Model response does not include A, B, C, D, or E at the end.")

# Generated by ChatGPT
def extract_keywords_from_answer(model_response: str) -> List[str]:
    '''Extracts the keywords from the model response.
    Handles various formats like:
    - Comma-separated keywords
    - Numbered or bulleted lists
    - Line-separated keywords
    - Mixed text with keywords
    
    Args:
        response_text (str): The raw text returned by the LLM.

    Returns:
        List[str]: A cleaned list of keywords.
    '''
    # Normalize line endings and remove leading/trailing whitespace
    text = model_response.strip().replace('\r\n', '\n')

    # Try to extract anything that looks like a list of keywords
    # e.g., "Keywords: apple, banana, orange"
    keyword_block = re.search(r"(keywords?\s*[:\-])\s*(.+)", text, re.IGNORECASE | re.DOTALL)
    if keyword_block:
        text = keyword_block.group(2).strip()

    # Split by newlines or commas, clean up numbers/bullets
    raw_keywords = re.split(r'[\n,]+', text)

    cleaned_keywords = []
    for kw in raw_keywords:
        # Remove bullets or numbers like "1.", "-", "*", etc.
        kw = re.sub(r"^\s*(?:[-*•]|\d+\.)\s*", "", kw)
        # Remove trailing punctuation
        kw = kw.strip().rstrip(".;:")
        if kw:
            cleaned_keywords.append(kw)

    return cleaned_keywords

def save_prompts_to_file(dataset_file: str, result_file:str) -> None:
    '''Applies the answer_prompt to all questions in the dataset and saves the prompts to a file. This will be used to asses GUI based models like ChatGPT.'''

    import pandas as pd
    from src.prompts import get_answer_prompt

    df = pd.read_csv(dataset_file)
    prompts = []
    correct_answers = []

    for i, row in df.iterrows():
        question = row['prompt']
        choices = [row['A'], row['B'], row['C'], row['D'], row['E']]
        context = ""
        answer = row['answer']
        prompt = get_answer_prompt(question, choices, context)
        prompts.append(prompt)
        correct_answers.append(answer)

    with open(result_file, 'w', encoding="utf8") as f:
        f.write('\n\n\n\n'.join(prompts))
    
    with open(result_file.replace('.txt', '_correct_answers.txt'), 'w', encoding="utf8") as f:
        f.write(', '.join(correct_answers))

def get_correct_answers(dataset_file: str) -> List[str]:
    '''Gets the correct answers from the dataset file.

    Args:
        dataset_file (str): The file containing the dataset.

    Returns:
        List[str]: The correct answers.
    '''

    import pandas as pd

    df = pd.read_csv(dataset_file)
    correct_answers = []

    for i, row in df.iterrows():
        correct_answers.append(row['answer'])

    return correct_answers